# Generated by Django 3.1.2 on 2020-10-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0004_auto_20201031_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='author',
        ),
    ]
